#!/usr/bin/env python

import sys

print ("Starting commit-msg hook")

# opening the file in read mode

newFileReplacement = ""
scoreFind = "You have passed"
string1 = "- ["

scoreIndex = 1
index = 1



#Finding score from report page 
file = open("calculator1Report.md", "r")
for line in file:
    line = line.strip()

    if scoreFind in line:
        score = line[-17];
        break;
    scoreIndex += 1
print(index)
print(scoreIndex , "The number found: " , score)
file.close()

file = open("calculator1Report.md", "r")
startline = 99999
foundLine = false

#using the for loop to find the line where it displays the tasks
for line in file:
    line = line.strip()

    #Change while the line read is under the score value
    #If user got 4 test passed, reads 4 lines from where the first - [ is
    if string1 in line:
        if foundLine = false:
            startline = index
        if startline <= int(score):
            index += 1
            changes = line.replace("- [ ]", "- [x]")
            newFileReplacement = newFileReplacement + changes + "\n"
        else: 
            newFileReplacement = newFileReplacement + line + "\n"
        index += 1
  
        

file.close()
# opening the file in write mode

fout = open("calculator1Report.md", "w")
fout.write(newFileReplacement)
fout.close()


sys.exit(0) #0 indicates success
