#!/usr/bin/env python

import sys

print ("Starting commit-msg hook")

# opening the file in read mode
file = open("calculator1Report.md", "r")
newFileReplacement = ""
string1 = "- [ ]"
index = 0

#using the for loop
for line in file:
    line = line.strip()

    if string1 in line:
      index += 1 
    changes = line.replace("[x]", "[ ]")
    newFileReplacement = newFileReplacement + changes + "\n"

print(index)
file.close()
# opening the file in write mode
fout = open("calculator1Report.md", "w")
fout.write(newFileReplacement)
fout.close()


sys.exit(0) #0 indicates success
